name: Deploy Node.js to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: azureappgit
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7B1B4FBF275044BCA0C413EB5466EA8E }}
          package: .
